title: Predicting League of Legends Match Outcomes
description: Analyzing League of Legends match outcomes using early-game statistics.
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Additional Customization Options
show_downloads: false # Hides download links (optional)
show_navbar: true # Displays a navigation bar
